# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-13 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=models.TextField(blank=True, max_length=700),
        ),
    ]
