# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-16 06:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0003_auto_20191014_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default=b'', max_length=255, null=True, upload_to=b'profile/')),
                ('phone', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(default=b'', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
