# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-16 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20191016_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default=b'', max_length=255, null=True, upload_to=b'profile/'),
        ),
    ]
